/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Graduation Design Service - version 1
 *
 * Graduation Design Service API
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'AuthController.queryCode': ['POST', '/auth/code'],
  'AuthController.confirm': ['GET', '/auth/confirm'],
  'AuthController.logout': ['GET', '/auth/logout'],
  'AuthController.resetPassword': ['PUT', '/auth/password'],
  'AuthController.signIn': ['POST', '/auth/sign_in'],
  'AuthController.signUp': ['POST', '/auth/sign_up'],
  'CanteenController.createCanteen': ['POST', '/canteen'],
  'CanteenController.listEveryStallNumber': ['GET', '/canteen/every/stall_number'],
  'CanteenController.listEveryStallFoodCount': ['GET', '/canteen/every_stall/food/number'],
  'CanteenController.listCanteen': ['GET', '/canteen/list'],
  'CanteenController.getCanteenNumber': ['GET', '/canteen/number'],
  'CanteenController.pageCanteen': ['GET', '/canteen/page'],
  'CanteenController.updateCanteen': ['PUT', '/canteen/{id}'],
  'CanteenController.deleteCanteen': ['DELETE', '/canteen/{id}'],
  'CanteenController.allocationCanteen': ['PATCH', '/canteen/{id}/user/{userId}'],
  'DictController.queryDict': ['GET', '/dict'],
  'DictController.queryDictTypes': ['GET', '/dict/type'],
  'DictController.queryDataByTypeId': ['GET', '/dict/{typeId}'],
  'FoodController.createFood': ['POST', '/food'],
  'FoodController.listFood': ['GET', '/food/list'],
  'FoodController.getFoodNumber': ['GET', '/food/number'],
  'FoodController.pageFood': ['GET', '/food/page'],
  'FoodController.uploadPicture': ['POST', '/food/picture'],
  'FoodController.recommendation': ['GET', '/food/recommendation'],
  'FoodController.updateFood': ['PUT', '/food/{id}'],
  'FoodController.updateFoodPrice': ['PATCH', '/food/{id}'],
  'FoodController.deleteFood': ['DELETE', '/food/{id}'],
  'ObjectController.imageFetch': ['GET', '/images/**'],
  'OrderController.getOrderStatus': ['GET', '/order/status/{code}'],
  'OrderController.uploadOrder': ['POST', '/order/upload'],
  'OrderController.getOrderItem': ['GET', '/order/{id}/order_item'],
  'RoleController.queryRoles': ['GET', '/role'],
  'SalesController.listCanteenRanking': ['GET', '/sales/list/canteen/ranking'],
  'SalesController.listCanteenHistorySales': ['GET', '/sales/list/canteen/stall/history'],
  'SalesController.listCanteenStallRanking': ['GET', '/sales/list/canteen/stall/ranking'],
  'SalesController.listEveryStallYesterdaySales': ['GET', '/sales/list/canteen/stall/yesterday'],
  'SalesController.listEveryCanteenYesterdaySales': ['GET', '/sales/list/canteen/yesterday'],
  'SalesController.listStallFoodRanking': ['GET', '/sales/list/stall/food/ranking'],
  'SalesController.listEveryFoodYesterdaySales': ['GET', '/sales/list/stall/food/yesterday'],
  'SalesController.listStallHistorySales': ['GET', '/sales/list/stall/history'],
  'StallController.createStall': ['POST', '/stall'],
  'StallController.listEveryFoodNumber': ['GET', '/stall/every/food_number'],
  'StallController.listStall': ['GET', '/stall/list'],
  'StallController.getStallNumber': ['GET', '/stall/number'],
  'StallController.pageStall': ['GET', '/stall/page'],
  'StallController.updateStall': ['PUT', '/stall/{id}'],
  'StallController.deleteStall': ['DELETE', '/stall/{id}'],
  'StallController.allocationCanteen_2': ['PATCH', '/stall/{id}/user/{userId}'],
  'TestController.getCaptcha': ['GET', '/test/captcha'],
  'UserController.queryUserInfo': ['GET', '/user'],
  'UserController.uploadAvatar': ['POST', '/user/avatar'],
  'UserController.updateEmail': ['PUT', '/user/email'],
  'UserController.importUser': ['POST', '/user/import'],
  'UserController.pageUser': ['GET', '/user/page'],
  'UserController.updatePassword': ['PUT', '/user/password'],
  'UserController.updateUserRole': ['PUT', '/user/role'],
  'UserController.deleteUser': ['DELETE', '/user/{id}'],
  'UserController.resetUserPassword': ['PATCH', '/user/{userId}'],
  'WebhookController.handleNotify': ['POST', '/webhook/alipay/notify']
};
